name: CI

on:
  push:
    branches: 
      "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ${{ env.MAIN_IMAGE }}
          platforms: ${{ env.PLATFORM }}
          cache-from: ${{ env.MAIN_IMAGE }}
          build-args: BUILDKIT_INLINE_CACHE=1
